### ISSUE TITLE
player variable always scope "room"

### ISSUE THREAD

**Issue by highno** [workadventure/workadventure#3520]
I create a player variable with this snippet:

```
		WA.player.state.saveVariable("roomHistory", roomHistory, {
		  public: true,
		  persist: true,
		  ttl: 24*3600,
		  scope: "world"
		});
```
roomHistory being an object like this:
```
	var roomHistory = {
		lastRoom : "",
		thisRoom : ""
	};
```
Though explicitly specified as scope "world" as depicted in API reference at https://docs.workadventu.re/developer/map-scripting/references/api-player/#setting-a-player-variable it creates a room scoped user-property.
Browser's local storage shows it like this:
key: user-properties__/global/play-workadventure.innoxlab.de/map-storage/a/map.json__|__roomHistory
value: 1696091643322:1:{"lastRoom":"","thisRoom":"https://play-workadventure.innoxlab.de/map-storage/a/map.json"}

I believe this is a bug.

**Comment by moufmouf** [comment]
Hey @highno ,

Thanks for reporting this.

Looking at the code, I think the behaviour comes from here: https://github.com/thecodingmachine/workadventure/blob/724fe34d6d71982c5f4e8a329d2994ea3f5590cf/play/src/front/Phaser/Game/PlayerVariablesManager.ts#L43-L50

Basically, when you use a URL starting with "/_/" (this is a default when you self-host), you don't have any "world ID". Each map is considered to be part of a different world. Therefore, the "world" setting does not work.

We did that for a pretty good reason (an attacker could redirect a victim to your server, but on a map that he controls, and steal the user variables).
That being said, now that we have a map-editor (on maps starting with "/~/"), we could put all those maps in the same world. I don't think we do it yet, but this is room for improvement.

**Comment by highno** [comment]
Thanks for the insight in this behavior. I unterstand the security impact but I don't want to change URLs again. People do bookmark their rooms a lot in my place...

Is there another way to fix this (like setting a global worldId in the container of a selfhosted version)? If this would be a possible "fix", I'll try to create a PR for this. 

The major security issue should be more obvious in the docs I'd say. There should be a short info on filtering URLs with a reverse proxy to only allow your own map server. 

I know that the major direction of maps is the internal map editor. We don't use that yet because you would need user authentication which we didn't implement yet at our site.

**Comment by highno** [comment]
That would be a workaround that might work. I would love to see a better fix not requiring to temper manually with "local storage".

**Comment by moufmouf** [comment]
Just implemented the "one single world" for maps from the map-storage.

I don't think we will do anything special for the public maps (starting with /_/). I'd rather avoid adding to many special cases and anyway, the standard way of designing a map will become through the map-editor/map-storage container as WorkAdventure progresses.

I'll mark this as closed, but don't hesitate to continue discussing here or in another issue if you want.

Closed by https://github.com/workadventure/workadventure/pull/3538

**Comment by highno** [comment]
Ok, the workaround using "localStorage" does not work because of this error:
DOMException: Failed to read the 'localStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag.
I basically understand the error but have no clue on how to fix it.

**Comment by moufmouf** [comment]
Alright. Indeed, the default script is "sandboxed" (because it is loaded from an HTML page in the domain of workadventure itself).

To solve this, you need to load the script from an embedded iframe (that you can host next to your map) as explained here: https://docs.workadventu.re/developer/map-scripting/scripting-internals#script-restrictions


The process goes like this:

- You create a web page (script.html) for instance
- This web page loads the scripting API (https://play.workadventu.re/iframe_api.js) + your own script ("src/main.ts")
- You modify the Vite configuration so that it takes your "script.html" page as an entry point.
- Now, you embed this "script.html" page into your map (https://docs.workadventu.re/map-building/tiled-editor/website-in-map) without forgetting to add the "allowApi: true" property.
- Now that your script is loaded from your own (non sandboxed) iframe , you go to Tiled, "Map > Properties", and you remove the "script" property.
