### ISSUE TITLE
turnserver dynamic credentials support

### ISSUE THREAD

**Issue by klauserber** [workadventure/workadventure#4332]
My coturn server ist configured with dynamic credentials (use-auth-secret) and works fine with jitsi and synapse. It is not possible to configure a coturn server with dynamic credentials an long term credentials at the same time.

WA supports only long term credentials. So I cannot use the same coturn instance for WA.

It would be nice to have dynamic credentials support in WA, which is also very much better from the security point of view.

**Comment by moufmouf** [comment]
Wait... WA does support dynamic credentials and has supported those since the start! :)

https://github.com/workadventure/workadventure/blob/develop/contrib/docker/.env.prod.template#L96-L99

If something is not clear (maybe the documentation?), don't hesitate to propose a PR to make this more obvious.

**Comment by klauserber** [comment]
Ah, very cool! I have overlooked it. Will test it in my setup ASAP.

**Comment by klauserber** [comment]
Just works! :-)
